QL_CDC/Models/TAI_KHOAN.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace QL_CDC.Models
{
    public partial class TAI_KHOAN
    {
        public TAI_KHOAN()
        {
            HOC_PHAN_THIs = new HashSet<HOC_PHAN_THI>();
            NHOM_THIs = new HashSet<NHOM_THI>();
            THONG_BAOs = new HashSet<THONG_BAO>();
        }

        public string ID_TK { get; set; }
        public string DN_TK { get; set; }
        public string MK_TK { get; set; }
        public string HOTEN_TK { get; set; }
        public DateTime? NGAYTAO_TK { get; set; }
        public string EMAIL_TK { get; set; }
        public DateTime? LANHDCUOI_TK { get; set; }
        public string ANHDAIDIEN_TK { get; set; }
        public bool? HOATDONG_TK { get; set; }
        public bool? LAADMIN_TK { get; set; }

        public virtual ICollection<HOC_PHAN_THI> HOC_PHAN_THIs { get; set; }
        public virtual ICollection<NHOM_THI> NHOM_THIs { get; set; }
        public virtual ICollection<THONG_BAO> THONG_BAOs { get; set; }
    }
}

QL_CDC/Controllers/TaiKhoanController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QL_CDC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace QL_CDC.Controllers
{
    public class TaiKhoanController : Controller
    {
        QL_CDCContext db = new QL_CDCContext();

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        [ActionName("DangNhap")]
        public IActionResult TaskDangNhap(DangNhapModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else
            {
                SINHVIEN sv = db.SINHVIENs.Where(x => x.SV_MSSV == model.MSSV).FirstOrDefault();
                if (sv == null)
                {
                    ModelState.AddModelError(nameof(DangNhapModel.MSSV), "*null");
                    return View(model);
                }
                else
                {
                    var mk = MaHoaMatKhau(model.MatKhau);
                    if (mk != sv.SV_MATKHAU)
                    {
                        ModelState.AddModelError(nameof(DangNhapModel.MSSV), "*mật khẩu");
                        return View(model);
                    }
                    else
                    {
                        string role = "";
                        if (sv.SV_ADMIN == true)
                        {
                            role = "ad";
                        }
                        else
                        {
                            role = "sv";
                        }
                        var claims = new[] {
                    new Claim(ClaimTypes.Name, sv.SV_TENHIENTHI),
                    new Claim(ClaimTypes.NameIdentifier, sv.SV_MSSV),
                    new Claim(ClaimTypes.Role, role)};
                        var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        HttpContext.SignInAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(identity));

                        db.Entry(sv).State = Microsoft.EntityFrameworkCore.EntityState.Detached;
                        sv.SV_LANHDCUOI = DateTime.Today;
                        db.Entry(sv).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                        db.SaveChanges();

                        return RedirectToAction("Index", "SanPham");
                    }
                }
            }
        }

        public string MaHoaMatKhau(string mk)
        {
            string mkmh = "";
            using var sha256 = SHA256.Create();
            byte[] bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(mk));
            var sb = new StringBuilder();
            for (int i = 0; i < bytes.Length; i++)
            {
                sb.Append(bytes[i].ToString("x2"));
            }
            mkmh = sb.ToString();
            return mkmh;
        }

        [Authorize]
        public async Task<IActionResult> DangXuat()
        {  
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index","SanPham");
        }

        public IActionResult LayIDUser()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return Json(id);
        }

        public IActionResult Test()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DangKy()
        {
            return View();
        }

        public IActionResult KiemTraTonTaiMSSV(string mssv)
        {
            SINHVIEN S = db.SINHVIENs.Where(a => a.SV_MSSV == mssv).FirstOrDefault();
            if(S == null)
            {
                return Json(false);
            }
            else
            {
                return Json(true);
            }
        }

        [HttpPost]
        [ActionName("DangKy")]
        [ValidateAntiForgeryToken]
        public IActionResult TaskDangKy(SinhVienModel model)
        {
            SINHVIEN sv = db.SINHVIENs.Where(a => a.SV_MSSV == model.MSSV).FirstOrDefault();
            if(sv != null)
            {
                ModelState.AddModelError(nameof(SinhVienModel.MSSV), "*MSSV này đã được đăng ký");
                return View(model);
            }
            else
            {
                sv = new SINHVIEN()
                {
                    SV_MSSV = model.MSSV,
                    SV_MATKHAU = MaHoaMatKhau(model.MatKhau),
                    SV_HOTEN = model.HoTen,
                    SV_TENHIENTHI = model.HoTen,
                    SV_NGAYTAOTK = DateTime.Today,
                    SV_LANHDCUOI = DateTime.Today,
                    SV_DIACHIGIAOHANG = model.DiaChi,
                    SV_SDT = model.SDT,
                    SV_EMAIL = model.Email,
                    SV_TINHTRANG = true,
                    SV_ADMIN = false,
                };
                db.SINHVIENs.Add(sv);
                db.SaveChanges();
                return RedirectToAction("DangNhap");
            }
        }

        [Authorize]
        public IActionResult ThongTinTaiKhoan()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            SINHVIEN SV = db.SINHVIENs.Where(a => a.SV_MSSV == id).FirstOrDefault();
            SinhVienModel model = new SinhVienModel()
            {
                MSSV = SV.SV_MSSV,
                HoTen = SV.SV_HOTEN,
                TenHienThi = SV.SV_TENHIENTHI,
                DiaChi = SV.SV_DIACHIGIAOHANG,
                SDT = SV.SV_SDT,
                Email = SV.SV_EMAIL
            };
            return View(model);
        }

        public IActionResult SuaThongTin(string tenhienthi, string email, string sdt, string hoten, string dc)
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            SINHVIEN sv = db.SINHVIENs.Where(a => a.SV_MSSV == id).FirstOrDefault();
            db.Entry(sv).State = Microsoft.EntityFrameworkCore.EntityState.Detached;
            sv.SV_TENHIENTHI = tenhienthi;
            sv.SV_EMAIL = email;
            sv.SV_SDT = sdt;
            sv.SV_HOTEN = hoten;
            sv.SV_DIACHIGIAOHANG = dc;
            db.Entry(sv).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();
            return Json("");
        }
    }       
}

QL_CDC/Views/TaiKhoan/DangKy.cshtml
@model SinhVienModel
@{
    ViewData["Title"] = "DangKy";
    Layout = null;
}

<link href="/template/css/style.css" rel="stylesheet">
<div class="container-fluid mb-5">
    <div class="row border-top px-xl-5">
        <div class="col-lg-12">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="@Url.Action("Index","SanPham")" class="text-decoration-none">
                            <h2 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">CDC</span>ChoDoCu</h2>
                        </a>
                    </div>
                    <div class="navbar-nav ml-auto py-0">
                        <a href="@Url.Action("DangNhap","TaiKhoan")" class="nav-item nav-link dndk">Đăng nhập</a>
                        <a href="@Url.Action("DangKy","TaiKhoan")" class="nav-item nav-link dndk" style="color: #0f893b">Đăng ký</a>
                    </div>
                </div>
            </nav>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <form asp-action="DangKy" method="post">
                <div id="dndkdiv">
                    <table class="dndktable" style="margin-top:0vh">
                        <tr>
                            <td>
                                <label asp-for="MSSV" class="labeldn" style="color: #0f893b;"></label>
                            </td>
                            <td>
                                <input asp-for="MSSV" type="text" class="form-control" id="mssv" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="MSSV" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b;">Họ và Tên: </label>
                            </td>
                            <td>
                                <input asp-for="HoTen" type="text" class="form-control" id="hoten" />
                            </td>
                        </tr>

                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="HoTen" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b;">Mật khẩu: </label>
                            </td>
                            <td>
                                <input asp-for="MatKhau" type="password" class="form-control" id="mk" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="MatKhau" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b;">Xác nhận mật khẩu: </label>
                            </td>
                            <td>
                                <input asp-for="XacNhanMatKhau" type="password" class="form-control" id="xnmk" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="XacNhanMatKhau" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b;">SĐT: </label>
                            </td>
                            <td>
                                <input asp-for="SDT" type="text" class="form-control" id="sdt" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="SDT" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b;">Email: </label>
                            </td>
                            <td>
                                <input asp-for="Email" type="text" class="form-control" id="email" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="Email" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b;">Địa chỉ: </label>
                            </td>
                            <td>
                                <textarea asp-for="DiaChi" class="form-control" id="dc"></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td>
                                <button type="submit" class="btn btn-primary btn-plus" style="margin-top: 20px; float: right">Đăng ký</button>
                            </td>
                        </tr>
                    </table>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

QL_CDC/Views/TaiKhoan/DangNhap.cshtml
@model DangNhapModel
@{
    ViewData["Title"] = "DangNhap";
    Layout = null;
}
<script src="~/js/jquery-3.3.1.min.js"></script>
<link href="/template/css/style.css" rel="stylesheet">
<div class="container-fluid mb-5">
    <div class="row border-top px-xl-5">

        <div class="col-lg-12">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a asp-action="Index" asp-controller="SanPham" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">CDC</span>ChoDoCu</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <a asp-action="Index" asp-controller="SanPham" class="text-decoration-none">
                        <h2 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">CDC</span>ChoDoCu</h2>
                    </a>
                    <div class="navbar-nav ml-auto py-0">
                        <a href="@Url.Action("DangNhap","TaiKhoan")" class="nav-item nav-link dndk" style="color: #0f893b">Đăng nhập</a>
                        <a href="@Url.Action("DangKy","TaiKhoan")" class="nav-item nav-link dndk">Đăng ký</a>
                    </div>
                </div>
            </nav>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <form asp-action="DangNhap" method="post">
                <div id="dndkdiv">
                    <table class="dndktable">
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b; font-size: 24px">MSSV: </label>
                            </td>
                            <td>
                                <input asp-for="MSSV" type="text" class="form-control" id="tk" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="MSSV" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label class="labeldn" style="color: #0f893b; font-size: 24px">Mật khẩu: </label>
                            </td>
                            <td>
                                <input asp-for="MatKhau" type="password" class="form-control" id="mk" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: left">
                                <span asp-validation-for="MatKhau" class="text-danger" style="margin-left: 10vw;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td style="text-align: center">
                                <button type="submit" class="btn btn-primary" style="margin-left: 10vw;margin-top: 20px">Đăng nhập</button>
                            </td>
                        </tr>
                    </table>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

QL_CDC/Views/TaiKhoan/Test.cshtml
@model QL_CDC.Models.SINHVIEN

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
</head>
<body>

<h4>SINHVIEN</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Test">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SV_MSSV" class="control-label"></label>
                <input asp-for="SV_MSSV" class="form-control" />
                <span asp-validation-for="SV_MSSV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_MATKHAU" class="control-label"></label>
                <input asp-for="SV_MATKHAU" class="form-control" />
                <span asp-validation-for="SV_MATKHAU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_HOTEN" class="control-label"></label>
                <input asp-for="SV_HOTEN" class="form-control" />
                <span asp-validation-for="SV_HOTEN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_TENHIENTHI" class="control-label"></label>
                <input asp-for="SV_TENHIENTHI" class="form-control" />
                <span asp-validation-for="SV_TENHIENTHI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_NGAYTAOTK" class="control-label"></label>
                <input asp-for="SV_NGAYTAOTK" class="form-control" />
                <span asp-validation-for="SV_NGAYTAOTK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_LANHDCUOI" class="control-label"></label>
                <input asp-for="SV_LANHDCUOI" class="form-control" />
                <span asp-validation-for="SV_LANHDCUOI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_DIACHIGIAOHANG" class="control-label"></label>
                <input asp-for="SV_DIACHIGIAOHANG" class="form-control" />
                <span asp-validation-for="SV_DIACHIGIAOHANG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_SDT" class="control-label"></label>
                <input asp-for="SV_SDT" class="form-control" />
                <span asp-validation-for="SV_SDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_EMAIL" class="control-label"></label>
                <input asp-for="SV_EMAIL" class="form-control" />
                <span asp-validation-for="SV_EMAIL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_TINHTRANG" class="control-label"></label>
                <input asp-for="SV_TINHTRANG" class="form-control" />
                <span asp-validation-for="SV_TINHTRANG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SV_ADMIN" class="control-label"></label>
                <input asp-for="SV_ADMIN" class="form-control" />
                <span asp-validation-for="SV_ADMIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

QL_CDC/Views/TaiKhoan/ThongTinTaiKhoan.cshtml
@model SinhVienModel 
@{
    ViewData["Title"] = "ThongTinTaiKhoan";
    Layout = "~/Views/Shared/_ThirdLayout.cshtml";
}

<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Thông tin cá nhân</span></h2>
    </div>
    <div class="row px-xl-5 pb-3 thongtincanhan">
        <div class="col-lg-12">
            <div class="mb-4">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label>MSSV</label>
                        <input class="form-control" type="text" placeholder="" value="@Model.MSSV" id="input1" disabled>
                    </div>
                    <div class="col-md-6 form-group">
                        <label>Tên hiển thị</label>
                        <input asp-for="TenHienThi" class="form-control" type="text" placeholder="" value="@Model.TenHienThi" id="input2" disabled>
                    </div>
                    <div class="col-md-6 form-group">
                        <label>E-mail</label>
                        <input asp-for="Email" class="form-control" type="text" placeholder="" value="@Model.Email" id="input3" disabled>
                    </div>
                    <div class="col-md-6 form-group">
                        <label>Số điện thoại</label>
                        <input asp-for="SDT" class="form-control" type="text" placeholder="" value="@Model.SDT" id="input4" disabled oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
                    </div>
                    <div class="col-md-6 form-group">
                        <label>Họ và tên</label>
                        <input asp-for="HoTen" class="form-control" type="text" placeholder="" value="@Model.HoTen" id="input5" disabled>
                    </div>
                    <div class="col-md-6 form-group">
                    </div>
                    <div class="col-md-12 form-group">
                        <label>Địa chỉ giao hàng</label>
                        <textarea asp-for="DiaChi" class="form-control" placeholder="Nhập địa chỉ giao hàng của bạn" id="input6" style="min-height: 20vh;" disabled>@Model.DiaChi</textarea>
                    </div>

                    <div class="col-md-12 form-group" style="text-align: right" id="bar-button">
                        <button class="btn btn-primary" onclick="ChinhSua()">Chỉnh sửa</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Products End -->

<script>


    // Luu
    function Luu() {
        var values = [];
        for (var i = 1; i < 7; i++) {
            values[i] = document.getElementById('input' + i).value;
        }
        $.ajax({
            url: '/TaiKhoan/SuaThongTin',
            type: 'post',
            data: {
                tenhienthi: values[2],
                email: values[3],
                sdt: values[4],
                hoten: values[5],
                dc: values[6],
            },
            success: function () {
                window.location.reload();
            }
        })
    }

    // Huy
    function Huy() {
        window.location.reload();
    }

    // Chinh sua
    function ChinhSua() {
        for (var i = 2; i < 7; i++) {
            document.getElementById('input' + i).disabled = false;
        }
        document.getElementById('input2').focus();

        str = '<button class="btn btn-primary" onclick="Luu()" style="margin-right: 30px">Lưu</button>'
        str += '<button class="btn btn-primary" onclick="Huy()">Hủy</button>'
        document.getElementById('bar-button').innerHTML = str
    }
</script>