QL_CDC/Controllers/CuaHangController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using QL_CDC.Models;
using System.Security.Claims;
using System.Dynamic;
using Microsoft.AspNetCore.Http;
using System.IO;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp;

namespace QL_CDC.Controllers
{
    public class CuaHangController : Controller
    {
        QL_CDCContext db = new QL_CDCContext();

        [Authorize]
        public IActionResult DanhSachSanPham()
        {
            List<SanPhamModel> SP = new List<SanPhamModel>();
            foreach(var item in db.SANPHAMs.Where(a => a.SV_MSSV == User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                SanPhamModel sp = new SanPhamModel() {
                    masp = item.SP_MSSP,
                    tensp = item.SP_TENSP,
                    anhsp = db.HINHANHs.Where(a => a.SP_MSSP == item.SP_MSSP).Select(a => a.HA_LINK).ToList(),
                    giagocsp = (double)item.SP_GIA,
                    ngaydangsp = ((DateTime)item.SP_NGAYDANG).ToString("dd/MM/yyyy"),
                    soluongsp = (int)item.SP_CONLAI,
                    luotxemsp = (int)item.SP_LUOTXEM,
                };
                SP.Add(sp);
            }
            return View(SP);
        }

        [Authorize]
        public IActionResult SuaSanPham(string id)
        {
            SANPHAM SP = db.SANPHAMs.Where(a => a.SP_MSSP == id).FirstOrDefault();
            dynamic model = new ExpandoObject();

            List<SelectListModel> L = new List<SelectListModel>();
            foreach (var x in db.LOAIMATHANGs)
            {
                SelectListModel s = new SelectListModel();
                s.id = x.MH_MAMH;
                s.name = x.MH_TENMH;
                L.Add(s);
            }
            model.mh = L;

            List<SelectListModel> L2 = new List<SelectListModel>();
            int mahang = db.LOAISANPHAMs.Where(a => a.LOAI_MALOAI == SP.LOAI_MALOAI).Select(a => a.MH_MAMH).FirstOrDefault();
            foreach (var x in db.LOAISANPHAMs.Where(a => a.MH_MAMH == mahang))
            {
                SelectListModel s = new SelectListModel();
                s.id = x.LOAI_MALOAI;
                s.name = x.LOAI_TENLOAI;
                L2.Add(s);
            }
            model.ml = L2;

            SanPhamModel sp = new SanPhamModel() {
                masp = SP.SP_MSSP,
                tensp = SP.SP_TENSP,
                maloai = SP.LOAI_MALOAI,
                giagocsp = (double)SP.SP_GIA,
                thoigiansp = (int)SP.SP_THOIGIANSUDUNG,
                soluongsp = (int)SP.SP_CONLAI,
                nsx = SP.SP_HANGSX,
                motasp = SP.SP_MOTA,
                anhsp = new List<string>(),
                mamh = db.LOAIMATHANGs.Where(a => a.MH_MAMH == SP.LOAI_MALOAINavigation.MH_MAMH).Select(a => a.MH_MAMH).FirstOrDefault(),
            };
            foreach(var str in db.HINHANHs.Where(a => a.SP_MSSP == sp.masp))
            {
                sp.anhsp.Add(str.HA_LINK);
            }
            model.sp = sp;

            return View(model);
        }

        [Authorize]
        public IActionResult LuuSuaSanPham(ThemSanPhamModel model)
        {
            SANPHAM S = db.SANPHAMs.Where(a => a.SP_MSSP == model.masp).FirstOrDefault();
            db.Entry(S).State = Microsoft.EntityFrameworkCore.EntityState.Detached;
            S.SP_TENSP = model.tensp;
            S.LOAI_MALOAI = model.maloai;
            S.SP_THOIGIANSUDUNG = model.tg;
            S.SP_GIA = model.gia;
            S.SP_CONLAI = model.sl;
            S.SP_HANGSX = model.nsx;
            S.SP_MOTA = model.mota;
            db.Entry(S).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();

            if (model.img != null)
            {
                foreach(var i in db.HINHANHs.Where(a => a.SP_MSSP == model.masp).ToList())
                {
                    FileInfo f = new FileInfo(Directory.GetCurrentDirectory() + "\\wwwroot" + i.HA_LINK);
                    f.Delete();
                    db.HINHANHs.Remove(i);
                    db.SaveChanges();
                }
                foreach (var i in model.img)
                {
                    HINHANH HA = new HINHANH()
                    {
                        HA_MSHA = Guid.NewGuid().ToString(),
                        SP_MSSP = model.masp,
                        HA_LINK = UploadImage(i),
                    };
                    db.HINHANHs.Add(HA);
                    db.SaveChanges();
                }
            }
            return Json(true);
        }
        public string UploadImage(IFormFile img)
        {
            var filename = Guid.NewGuid().ToString() + img.FileName;
            var filepath = Directory.GetCurrentDirectory() + "\\wwwroot\\sanpham\\" + filename;
            using var image = SixLabors.ImageSharp.Image.Load(img.OpenReadStream());
            image.Mutate(x => x.Resize(500, 500));
            image.Save(filepath);
            var report = "\\sanpham\\" + filename;
            return report;
        }
    }
}

QL_CDC/Views/CuaHang/DanhSachSanPham.cshtml
@model IEnumerable<SanPhamModel>
@{
    ViewData["Title"] = "DSSP";
    Layout = "~/Views/Shared/_SecondLayout.cshtml";

}

<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5 tuade"><span class="px-2">Cửa hàng</span></h2>
    </div>
    <div class="table-themsanpham" style="margin-top:2vh;">
        <div class="btnaddfile" style="width:30%" onclick="window.location.href = '/SanPham/ThemSanPham'">Thêm sản phẩm</div>
        <div style="width:70%"></div>
    </div>
    @foreach (var item in Model)
    {
        <div class="cuahangitem">
            <div class="cuahangimg">
                <img src="@item.anhsp[0]" class="hinhsanphamcuahang" />
            </div>
            <div class="cuahanginfo">
                <div class="cuahangten">
                    <p><strong>@item.tensp</strong></p>
                </div>
                <div class="cuahanginfo2">
                    <div class="cuahanggia">
                        <div class="cuahangdecor">
                            <div class="cuahangtuade">Ngày đăng</div>
                            <div class="cuahangso">@item.ngaydangsp</div>
                        </div>
                    </div>
                    <div class="cuahanggia">
                        <div class="cuahangdecor">
                            <div class="cuahangtuade">Giá</div>
                            @{ string giagoc = string.Format("{0:#,##0.########}", item.giagocsp);}
                            <div class="cuahangso">@giagoc Đ</div>
                        </div>
                    </div>
                    <div class="cuahanggia">
                        <div class="cuahangdecor">
                            <div class="cuahangtuade">Số lượng</div>
                            <div class="cuahangso">@item.soluongsp</div>
                        </div>
                    </div>
                    <div class="cuahanggia">
                        <div class="cuahangdecor">
                            <div class="cuahangtuade">Lượt xem</div>
                            <div class="cuahangso">@item.luotxemsp</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cuahangtuychon">
                <div class="cuahangdecor" style="margin-top:5%;margin-left:1%">
                    <i class="fa fa-pencil" onclick="CuaHangSuaSanPham('@item.masp')"></i>
                    <i class="fa fa-times" onclick="CuaHangXoaSanPham('@item.masp')"></i>
                </div>
            </div>
        </div>
    }
</div>

<script>
    // Sua san pham
    function CuaHangSuaSanPham(id) {
        window.location.href = '/CuaHang/SuaSanPham/' + id;
    }

    // Xoa san pham - con lai = 0
    function CuaHangXoaSanPham(id) {

    }
</script>

QL_CDC/Views/CuaHang/SuaSanPham.cshtml
@model dynamic
@{
    ViewData["Title"] = "SuaSanPham";
    Layout = "~/Views/Shared/_SecondLayout.cshtml";
}

<div class="container-fluid pt-5">
    <!--Ten-->
    <div class="text-center mb-4">
        <h2 class="section-title px-5 tuade"><span class="px-2">Chỉnh sửa sản phẩm</span></h2>
    </div>
    <div class="table-themsanpham">
        <div class="add_label">
            <label>Tên sản phẩm: </label>
        </div>
        <div class="add_input">
            <input type="text" id="add_ten" class="form-control" placeholder="Nhập tên của sản phẩm" value="@Model.sp.tensp"/>
        </div>
    </div>
    <!--Loai-->
    <div class="table-themsanpham2">
        <div class="add_label">
            <label>Loại: </label>

        </div>
        <div class="add_input_2">
            <select class="form-control" id="add_mh">
                <option value="0" style="text-align:center" disabled>--- Loại mặt hàng ---</option>
                @foreach (var item in Model.mh)
                {
                    if (Model.sp.mamh == item.id)
                    {
                        <option value="@item.id" selected>@item.name</option>
                    }
                    else
                    {
                        <option value="@item.id">@item.name</option>
                    }
                }
            </select>
        </div>
        <div class="add_label">

        </div>
        <div class="add_input_2">
            <select class="form-control" id="add_l">
                <option value="0" style="text-align:center" disabled>--- Loại sản phẩm ---</option>
                @foreach (var item in Model.ml)
                {
                    if (Model.sp.maloai == item.id)
                    {
                        <option value="@item.id" selected>@item.name</option>
                    }
                    else
                    {
                        <option value="@item.id">@item.name</option>
                    }
                }
            </select>
        </div>
    </div>
    <!--Thoi gian, gia-->
    <div class="table-themsanpham2">
        <div class="add_label">
            <label>Giá: </label>

        </div>
        <div class="add_input_number">
            <input type="text" id="add_gia" value="@Model.sp.giagocsp" class="form-control" placeholder="VND" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" />
        </div>
        <div style="width: 20%">

        </div>
        <div class="add_label">
            <label>Đã dùng trong: </label>

        </div>
        <div class="add_input_number">
            <input type="number" id="add_thoigian" value="@Model.sp.thoigiansp" min="0" class="form-control" placeholder="Tháng" />
        </div>
    </div>
    <!--So luong, nsx-->
    <div class="table-themsanpham2">
        <div class="add_label">
            <label>Số lượng: </label>

        </div>
        <div class="add_input_number">
            <input type="number" id="add_sl" min="0" class="form-control" value="@Model.sp.soluongsp" />
        </div>
        <div style="width: 20%">

        </div>
        <div class="add_label">
            <label>Nhà sản xuất: </label>

        </div>
        <div class="add_input_number">
            <input type="text" id="add_nsx" class="form-control" value="@Model.sp.nsx" />
        </div>
    </div>
    <!--Hinh anh-->
    <div class="table-themsanpham2">
        <div class="add_label">
            <label>Hình ảnh: </label>

        </div>
        <div class="add_input_file">
            <div class="btnaddfile" onclick="document.getElementById('add_file').click()">Tải ảnh lên</div>
            <input type="file" id="add_file" class="form-control add_file" multiple="multiple" accept=".png, .jpg, .jpeg" />
        </div>
    </div>
    <div class="table-themsanpham2" id="add_preview">
        @foreach(var img in Model.sp.anhsp)
            {
            <img src="@img" />
            }
    </div>
    <!--Mota-->
    <div class="table-themsanpham" style="margin-top:2vh">
        <div class="add_label" style="width:50%">
            <label>Mô tả sản phẩm: </label>
        </div>
    </div>
    <div class="table-themsanpham" style="margin-top:0vh">
        <textarea class="form-control" id="add_mota">@Model.sp.motasp</textarea>
    </div>
    <!--Nut-->
    <div class="table-themsanpham" style="margin-top:2vh;">
        <div style="width:40%"></div>
        <div class="btnaddfile" style="width:20%" onclick="LuuSuaSanPham()">Chỉnh sửa</div>
        <div style="width:40%"></div>
    </div>

</div>

<script>
    function commaSeparateNumber(val) {
        while (/(\d+)(\d{3})/.test(val.toString())) {
            val = val.toString().replace(/(\d+)(\d{3})/, '$1' + ',' + '$2');
        }
        return val;
    }
    $('#add_gia').focusout(function () {
        document.getElementById('add_gia').value = commaSeparateNumber($(this).val());
        if (parseInt(document.getElementById('add_gia').value) < 0) document.getElementById('add_gia').value = 0;
    });
    $('#add_sl').focusout(function () {
        var x = parseInt(document.getElementById('add_sl').value);
        if (x < 0) document.getElementById('add_sl').value = 0;
    });
    $('#add_thoigian').focusout(function () {
        var x = parseInt(document.getElementById('add_thoigian').value);
        if (x < 0) document.getElementById('add_thoigian').value = 0;
    });
    $('#add_mh').change(function () {
        CapNhatLoai($(this).val());
    })
    function CapNhatLoai(id) {
        document.getElementById('add_l').innerHTML = '<option value="0" style="text-align:center" selected disabled>--- Loại sản phẩm ---</option>';
        $.ajax({
            url: '/SanPham/CapNhatLoai',
            type: 'post',
            data: {
                id: id
            },
            async: false,
            success: function (data) {
                for (var i in data) {
                    var str = new Option(data[i].name, data[i].id);;
                    $('#add_l').append(str);
                }
            }
        })
    }
    $("#add_file").change(function () {
        document.getElementById('add_preview').innerHTML = "";
        readURL(this, $('#add_preview'));
        if (this.files.length > 5) {
            document.getElementById("add_preview").style.height = "23vh";
        }
        else {
            document.getElementById("add_preview").style.height = "20vh";
        }
    });
    function readURL(input, div) {
        if (input.files) {
            var filesAmount = input.files.length;
            for (i = 0; i < filesAmount; i++) {
                var reader = new FileReader();
                reader.onload = function (event) {
                    $($.parseHTML('<img>')).attr('src', event.target.result).appendTo(div);
                }
                reader.readAsDataURL(input.files[i]);
            }
        }
    }
    function KiemTraDuLieu(tensp, mahang, maloai, gia, tg, sl, nsx, img, mota) {
        var check = false;
        if (tensp == null || tensp == "") {
            alert("Vui lòng nhập tên sản phẩm")
        }
        else if (mahang == 0 || mahang == '0' || maloai == 0 || maloai == '0') {
            alert("Vui lòng chọn loại sản phẩm")
        }
        else if (gia == null || gia == 0 || gia == 0) {
            alert("Vui lòng nhập giá cho sản phẩm")
        }
        else if (tg == null) {
            alert("Vui lòng chọn thời gian đã sử dụng")
        }
        else if (sl == 0 || sl == '0' || sl == null) {
            alert("Vui lòng nhâp số lượng sản phẩm")
        }
        else if (document.getElementById('add_preview').innerHTML == "" ) {
            alert("Vui lòng thêm ít nhất một tấm ảnh cho sản phẩm");
        }
        else if (img > 10) {
            alert("Vui lòng chọn tối đa 10 tấm ảnh cho sản phẩm")
        }
        else {
            check = true;
        }
        return check;
    }
    function LuuSuaSanPham() {
        if (confirm("Sửa thông tin sản phẩm?")) {
            var tensp = document.getElementById('add_ten').value;
        var mahang = document.getElementById('add_mh').value;
        var maloai = document.getElementById('add_l').value;
        var gia = $('#add_gia').val();
        var tg = $('#add_thoigian').val();
        var sl = $('#add_sl').val();
        var nsx = $('#add_nsx').val();
        var img = document.getElementById('add_file').files;
        var mota = $('#add_mota').val();
        var masp = '@Model.sp.masp';

        if (KiemTraDuLieu(tensp, mahang, maloai, gia, tg, sl, nsx, img.length, mota)) {
            var formData = new FormData();
            formData.append("tensp", tensp);
            for (var i = 0; i < img.length; i++) {
                formData.append("img", img[i]);
            }
            formData.append("mahang", mahang);
            formData.append("maloai", maloai);
            formData.append("gia", gia);
            formData.append("tg", tg);
            formData.append("sl", sl);
            formData.append("nsx", nsx);
            formData.append("mota", mota);
            formData.append("masp", masp);

            $.ajax({
                url: '/CuaHang/LuuSuaSanPham',
                type: 'post',
                async: true,
                dataType: 'json',
                processData: false,
                contentType: false,
                data: formData,
                success: function (data) {
                    window.location.href = '/CuaHang/SuaSanPham/' + masp;
                },
                error: function () {
                    // window.location.href = '/CuaHang/SuaSanPham/' + masp;
                }
            })
        }
        }
    }
</script>

QL_CDC/Views/CuaHang/_DieuKhienCuaHangPartial.cshtml
<a href="@Url.Action("DanhSachSanPham","CuaHang")" class="nav-item nav-link dndk">Sản phẩm  <i class="fa fa-bars mr-1"></i></a>
<a href="@Url.Action("DanhSachHoaDonNguoiBan","HoaDon")" class="nav-item nav-link dndk">Hóa đơn  <i class="fa fa-file-text mr-1"></i><small id="HoaDonMoi"></small></a>

<script>
    // Dem hoa don moi
    function SoHoaDonMoi() {
        $.ajax({
            url: '/HoaDon/DemHoaDonMoi',
            type: 'get',
            success: function (data) {
                if (parseInt(data) != 0) {
                    document.getElementById('HoaDonMoi').innerHTML = '( ' + data + ' )';
                    document.getElementById('HoaDonMoi').style.color = "red";
                }
            }
        })
    }

    //ready
    $(document).ready(function () {
        SoHoaDonMoi();
    })
</script>